version: '3.7'

services:
  lesson-service_v1:
    image: stevenpadilla/lesson_service:1.3.0
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: lesson-service
    env_file:
      - .env
    expose:
      - '1709'
    ports:
      - '3003:1709'
    command: node dist/src/index.js